version: 2
updates:
  - package-ecosystem: gomod
    directory: /pkg # Location of package manifests
    schedule:
      interval: daily
    labels:
    - dependencies
  - package-ecosystem: gomod
    directory: /tools # Location of package manifests
    schedule:
      interval: weekly
    labels:
    - dependencies
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
