name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - README.md
      - .gitignore
  merge_group:

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21
    - name: Format check
      run: make fmt
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.59.1
        args: --build-tags testonly
    - name: Check generated code
      run: make generate
