name: Test and Coverage

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - README.md
      - .gitignore
  push:
    branches:
      - main
  merge_group:

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21
    - name: Generate coverage report
      run: make test
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
